namespace NuVatis.QueryBuilder.Tools.Generation;

using System.Text;
using NuVatis.QueryBuilder.Tools.Scanning;

public static class TableClassGenerator {
    private static readonly Dictionary<string, string> _pgTypeMap =
        new(StringComparer.OrdinalIgnoreCase) {
            ["int4"]              = "int",    ["int8"]    = "long",
            ["int2"]              = "short",  ["float4"]  = "float",
            ["float8"]            = "double", ["numeric"]  = "decimal",
            ["varchar"]           = "string", ["text"]     = "string",
            ["char"]              = "string", ["bpchar"]   = "string",
            ["bool"]              = "bool",   ["boolean"]  = "bool",
            ["timestamp"]         = "DateTime", ["timestamptz"] = "DateTime",
            ["date"]              = "DateOnly",  ["time"]   = "TimeOnly",
            ["uuid"]              = "Guid",   ["jsonb"]    = "string",
            ["json"]              = "string", ["bytea"]    = "byte[]",
            ["integer"]           = "int",    ["bigint"]   = "long",
            ["smallint"]          = "short",  ["real"]     = "float",
            ["double precision"]  = "double",
            ["character varying"] = "string", ["character"] = "string",
            ["serial"]            = "int",    ["bigserial"] = "long",
        };

    private static readonly Dictionary<string, string> _mysqlTypeMap =
        new(StringComparer.OrdinalIgnoreCase) {
            ["int"]       = "int",    ["bigint"]   = "long",
            ["smallint"]  = "short",  ["tinyint"]  = "byte",
            ["float"]     = "float",  ["double"]   = "double",
            ["decimal"]   = "decimal",["numeric"]  = "decimal",
            ["varchar"]   = "string", ["text"]     = "string",
            ["char"]      = "string", ["tinytext"]  = "string",
            ["mediumtext"]= "string", ["longtext"]  = "string",
            ["datetime"]  = "DateTime",["timestamp"] = "DateTime",
            ["date"]      = "DateOnly",["time"]     = "TimeOnly",
            ["bit"]       = "bool",   ["boolean"]  = "bool",
            ["json"]      = "string", ["blob"]     = "byte[]",
        };

    public static string Generate(TableInfo table, string ns, string provider = "postgresql") {
        var map       = provider == "mysql" ? _mysqlTypeMap : _pgTypeMap;
        var className = ToPascalCase(table.Name) + "Table";
        var sb        = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("using NuVatis.QueryBuilder.Ast;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {className} : TableNode {{");
        sb.AppendLine($"    public static readonly {className} Instance = new(\"{table.Schema}\", \"{table.Name}\");");
        sb.AppendLine($"    private {className}(string schema, string name) : base(schema, name) {{ }}");
        sb.AppendLine();

        foreach (var col in table.Columns) {
            var csType   = MapType(map, col.DbType, col.IsNullable);
            var propName = col.ColumnName.ToUpperInvariant();
            sb.AppendLine($"    public readonly FieldNode<{csType}> {propName} = new(Instance, \"{col.ColumnName}\");");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string GenerateTablesEntry(IReadOnlyList<TableInfo> tables, string ns) {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("public static class Tables {");
        foreach (var t in tables) {
            var className = ToPascalCase(t.Name) + "Table";
            var propName  = t.Name.ToUpperInvariant();
            sb.AppendLine($"    public static readonly {className} {propName} = {className}.Instance;");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string MapType(Dictionary<string, string> map, string dbType, bool nullable) {
        var csType = map.TryGetValue(dbType, out var t) ? t : "string";
        return (nullable && csType != "string" && csType != "byte[]") ? csType + "?" : csType;
    }

    public static string ToPascalCase(string s)
        => string.Concat(s.Split('_').Select(w =>
            w.Length > 0 ? char.ToUpperInvariant(w[0]) + w[1..] : w));
}
